version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eme-postgres
    environment:
      POSTGRES_DB: eme_cache
      POSTGRES_USER: eme_user
      POSTGRES_PASSWORD: eme_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
