package com.raidrin.eme.anki;

public enum CardType {
    SOURCE_TEXT,
    SOURCE_TRANSLITERATION,
    SOURCE_AUDIO,
    TARGET_TEXT,
    SENTENCE_LATIN,
    SENTENCE_TRANSLITERATION,
    SENTENCE_SOURCE,
    SENTENCE_STRUCTURE,
    SENTENCE_SOURCE_AUDIO,
    IMAGE,
    MNEMONIC_KEYWORD,
    MNEMONIC_SENTENCE,
    LINE_BREAK
}
