-- Seed the database with 100 common Hindi words and their translations/sentences

-- Insert translations (Hindi to English)
INSERT INTO translations (word, source_language, target_language, translations, created_at, updated_at) VALUES
('है', 'hi', 'en', '["is", "am", "are"]', NOW(), NOW()),
('में', 'hi', 'en', '["in"]', NOW(), NOW()),
('के', 'hi', 'en', '["of", "for"]', NOW(), NOW()),
('और', 'hi', 'en', '["and"]', NOW(), NOW()),
('यह', 'hi', 'en', '["this", "he", "she", "it"]', NOW(), NOW()),
('वह', 'hi', 'en', '["that", "he", "she", "it"]', NOW(), NOW()),
('का', 'hi', 'en', '["of", "''s"]', NOW(), NOW()),
('की', 'hi', 'en', '["of", "''s"]', NOW(), NOW()),
('को', 'hi', 'en', '["to", "object marker"]', NOW(), NOW()),
('हैं', 'hi', 'en', '["are"]', NOW(), NOW()),
('नहीं', 'hi', 'en', '["no", "not"]', NOW(), NOW()),
('से', 'hi', 'en', '["from", "by", "with"]', NOW(), NOW()),
('पर', 'hi', 'en', '["on", "at"]', NOW(), NOW()),
('कि', 'hi', 'en', '["that"]', NOW(), NOW()),
('आप', 'hi', 'en', '["you"]', NOW(), NOW()),
('मैं', 'hi', 'en', '["I"]', NOW(), NOW()),
('हूँ', 'hi', 'en', '["am"]', NOW(), NOW()),
('लिए', 'hi', 'en', '["for"]', NOW(), NOW()),
('करना', 'hi', 'en', '["to do"]', NOW(), NOW()),
('होना', 'hi', 'en', '["to be", "to happen"]', NOW(), NOW()),
('क्या', 'hi', 'en', '["what", "question marker"]', NOW(), NOW()),
('एक', 'hi', 'en', '["one", "a", "an"]', NOW(), NOW()),
('जो', 'hi', 'en', '["who", "which", "that"]', NOW(), NOW()),
('तो', 'hi', 'en', '["so", "then"]', NOW(), NOW()),
('ही', 'hi', 'en', '["only", "just"]', NOW(), NOW()),
('भी', 'hi', 'en', '["also", "too"]', NOW(), NOW()),
('था', 'hi', 'en', '["was"]', NOW(), NOW()),
('जाना', 'hi', 'en', '["to go"]', NOW(), NOW()),
('इस', 'hi', 'en', '["this"]', NOW(), NOW()),
('उस', 'hi', 'en', '["that"]', NOW(), NOW()),
('बहुत', 'hi', 'en', '["very", "much", "many"]', NOW(), NOW()),
('हम', 'hi', 'en', '["we"]', NOW(), NOW()),
('कोई', 'hi', 'en', '["someone", "anyone", "any"]', NOW(), NOW()),
('तक', 'hi', 'en', '["until", "up to"]', NOW(), NOW()),
('बात', 'hi', 'en', '["matter", "talk", "thing"]', NOW(), NOW()),
('आना', 'hi', 'en', '["to come"]', NOW(), NOW()),
('रहा', 'hi', 'en', '["continuous tense marker"]', NOW(), NOW()),
('अपना', 'hi', 'en', '["one''s own"]', NOW(), NOW()),
('कुछ', 'hi', 'en', '["some", "something"]', NOW(), NOW()),
('काम', 'hi', 'en', '["work", "task"]', NOW(), NOW()),
('समय', 'hi', 'en', '["time"]', NOW(), NOW()),
('लोग', 'hi', 'en', '["people"]', NOW(), NOW()),
('लेकिन', 'hi', 'en', '["but"]', NOW(), NOW()),
('अगर', 'hi', 'en', '["if"]', NOW(), NOW()),
('या', 'hi', 'en', '["or"]', NOW(), NOW()),
('घर', 'hi', 'en', '["home", "house"]', NOW(), NOW()),
('साथ', 'hi', 'en', '["with", "together"]', NOW(), NOW()),
('मेरा', 'hi', 'en', '["my", "mine"]', NOW(), NOW()),
('आपका', 'hi', 'en', '["your", "yours"]', NOW(), NOW()),
('सब', 'hi', 'en', '["all", "everything"]', NOW(), NOW()),
('मुझे', 'hi', 'en', '["me", "to me"]', NOW(), NOW()),
('देना', 'hi', 'en', '["to give"]', NOW(), NOW()),
('लेना', 'hi', 'en', '["to take"]', NOW(), NOW()),
('देखना', 'hi', 'en', '["to see", "to watch"]', NOW(), NOW()),
('अच्छा', 'hi', 'en', '["good", "well", "okay"]', NOW(), NOW()),
('बड़ा', 'hi', 'en', '["big", "large", "elder"]', NOW(), NOW()),
('दिन', 'hi', 'en', '["day"]', NOW(), NOW()),
('आज', 'hi', 'en', '["today"]', NOW(), NOW()),
('कल', 'hi', 'en', '["tomorrow", "yesterday"]', NOW(), NOW()),
('यहाँ', 'hi', 'en', '["here"]', NOW(), NOW()),
('वहाँ', 'hi', 'en', '["there"]', NOW(), NOW()),
('कहाँ', 'hi', 'en', '["where"]', NOW(), NOW()),
('कैसे', 'hi', 'en', '["how"]', NOW(), NOW()),
('कब', 'hi', 'en', '["when"]', NOW(), NOW()),
('क्यों', 'hi', 'en', '["why"]', NOW(), NOW()),
('कौन', 'hi', 'en', '["who"]', NOW(), NOW()),
('फिर', 'hi', 'en', '["again", "then"]', NOW(), NOW()),
('पानी', 'hi', 'en', '["water"]', NOW(), NOW()),
('खाना', 'hi', 'en', '["food", "to eat"]', NOW(), NOW()),
('बोलना', 'hi', 'en', '["to speak", "to say"]', NOW(), NOW()),
('सुनना', 'hi', 'en', '["to listen", "to hear"]', NOW(), NOW()),
('समझना', 'hi', 'en', '["to understand"]', NOW(), NOW()),
('जानना', 'hi', 'en', '["to know"]', NOW(), NOW()),
('चाहिए', 'hi', 'en', '["should", "need", "want"]', NOW(), NOW()),
('सकता', 'hi', 'en', '["can", "able to"]', NOW(), NOW()),
('पास', 'hi', 'en', '["near", "possession"]', NOW(), NOW()),
('अब', 'hi', 'en', '["now"]', NOW(), NOW()),
('पहले', 'hi', 'en', '["before", "first"]', NOW(), NOW()),
('बाद', 'hi', 'en', '["after"]', NOW(), NOW()),
('रात', 'hi', 'en', '["night"]', NOW(), NOW()),
('नाम', 'hi', 'en', '["name"]', NOW(), NOW()),
('छोटा', 'hi', 'en', '["small", "younger"]', NOW(), NOW()),
('नया', 'hi', 'en', '["new"]', NOW(), NOW()),
('क्योंकि', 'hi', 'en', '["because"]', NOW(), NOW()),
('इसलिए', 'hi', 'en', '["therefore", "so"]', NOW(), NOW()),
('हाँ', 'hi', 'en', '["yes"]', NOW(), NOW()),
('कृपया', 'hi', 'en', '["please"]', NOW(), NOW()),
('धन्यवाद', 'hi', 'en', '["thank you"]', NOW(), NOW()),
('पूछना', 'hi', 'en', '["to ask"]', NOW(), NOW()),
('बताना', 'hi', 'en', '["to tell"]', NOW(), NOW()),
('सोचना', 'hi', 'en', '["to think"]', NOW(), NOW()),
('चलना', 'hi', 'en', '["to walk", "to move", "to go"]', NOW(), NOW()),
('बैठना', 'hi', 'en', '["to sit"]', NOW(), NOW()),
('अंदर', 'hi', 'en', '["inside"]', NOW(), NOW()),
('बाहर', 'hi', 'en', '["outside"]', NOW(), NOW()),
('सुबह', 'hi', 'en', '["morning"]', NOW(), NOW()),
('शाम', 'hi', 'en', '["evening"]', NOW(), NOW()),
('हमेशा', 'hi', 'en', '["always"]', NOW(), NOW()),
('माफ़ कीजिए', 'hi', 'en', '["excuse me", "sorry"]', NOW(), NOW()),
('नमस्कार', 'hi', 'en', '["hello", "greetings", "goodbye"]', NOW(), NOW());

-- Insert sentence examples (Hindi to English)
INSERT INTO sentences (word, source_language, target_language, word_romanized, sentence_source, sentence_transliteration, sentence_target, word_structure, created_at, updated_at) VALUES
('है', 'hi', 'en', 'hai', 'यह क्या है?', 'Yah kya hai?', 'What is this?', 'This what is?', NOW(), NOW()),
('में', 'hi', 'en', 'mein', 'आप कमरे में हैं।', 'Aap kamre mein hain.', 'You are in the room.', 'You room in are.', NOW(), NOW()),
('के', 'hi', 'en', 'ke', 'आपके विचार अच्छे हैं।', 'Aapke vichaar acche hain.', 'Your thoughts are good.', 'Your thoughts good are.', NOW(), NOW()),
('और', 'hi', 'en', 'aur', 'आप और मैं यहाँ हैं।', 'Aap aur main yahaan hain.', 'You and I are here.', 'You and I here are.', NOW(), NOW()),
('यह', 'hi', 'en', 'yah', 'यह मेरी किताब है।', 'Yah meri kitaab hai.', 'This is my book.', 'This my book is.', NOW(), NOW()),
('वह', 'hi', 'en', 'vah', 'वह आपका घर है।', 'Vah aapka ghar hai.', 'That is your house.', 'That your house is.', NOW(), NOW()),
('का', 'hi', 'en', 'ka', 'इस कमरे का दरवाज़ा खुला है।', 'Is kamre ka darwaza khula hai.', 'This room''s door is open.', 'This room of door open is.', NOW(), NOW()),
('की', 'hi', 'en', 'ki', 'आपकी बात सही है।', 'Aapki baat sahi hai.', 'What you are saying is correct.', 'Your talk correct is.', NOW(), NOW()),
('को', 'hi', 'en', 'ko', 'कृपया डॉक्टर को बुलाइए।', 'Kripaya doctor ko bulaiye.', 'Please call the doctor.', 'Please doctor to call.', NOW(), NOW()),
('हैं', 'hi', 'en', 'hain', 'आप कैसे हैं?', 'Aap kaise hain?', 'How are you?', 'You how are?', NOW(), NOW()),
('नहीं', 'hi', 'en', 'nahin', 'जी नहीं, मुझे यह नहीं चाहिए।', 'Jee nahin, mujhe yah nahin chahiye.', 'No, I do not want this.', 'Respectful particle no, me this not want.', NOW(), NOW()),
('से', 'hi', 'en', 'se', 'आप कहाँ से हैं?', 'Aap kahaan se hain?', 'Where are you from?', 'You where from are?', NOW(), NOW()),
('पर', 'hi', 'en', 'par', 'आपकी किताब मेज़ पर है।', 'Aapki kitaab mez par hai.', 'Your book is on the table.', 'Your book table on is.', NOW(), NOW()),
('कि', 'hi', 'en', 'ki', 'उन्होंने कहा कि वे आएँगे।', 'Unhone kaha ki ve aayenge.', 'He/She said that they will come.', 'They said that they will come.', NOW(), NOW()),
('आप', 'hi', 'en', 'aap', 'क्या आप तैयार हैं?', 'Kya aap taiyaar hain?', 'Are you ready?', 'What you ready are?', NOW(), NOW()),
('मैं', 'hi', 'en', 'main', 'मैं आपकी बात समझता हूँ।', 'Main aapki baat samajhta hoon.', 'I understand what you are saying.', 'I your talk understand do.', NOW(), NOW()),
('हूँ', 'hi', 'en', 'hoon', 'मैं यहाँ हूँ।', 'Main yahaan hoon.', 'I am here.', 'I here am.', NOW(), NOW()),
('लिए', 'hi', 'en', 'liye', 'यह आपके लिए है।', 'Yah aapke liye hai.', 'This is for you.', 'This you for is.', NOW(), NOW()),
('करना', 'hi', 'en', 'karna', 'आप क्या काम करते हैं?', 'Aap kya kaam karte hain?', 'What work do you do?', 'You what work do?', NOW(), NOW()),
('होना', 'hi', 'en', 'hona', 'सब ठीक हो जाएगा।', 'Sab theek ho jaayega.', 'Everything will be alright.', 'Everything alright become will.', NOW(), NOW()),
('क्या', 'hi', 'en', 'kya', 'आपका नाम क्या है?', 'Aapka naam kya hai?', 'What is your name?', 'Your name what is?', NOW(), NOW()),
('एक', 'hi', 'en', 'ek', 'कृपया एक मिनट रुकिए।', 'Kripaya ek minute rukiye.', 'Please wait one minute.', 'Please one minute wait.', NOW(), NOW()),
('जो', 'hi', 'en', 'jo', 'जो व्यक्ति वहाँ खड़े हैं, वे मेरे मित्र हैं।', 'Jo vyakti vahaan khade hain, ve mere mitra hain.', 'The person who is standing there is my friend.', 'Who person there standing are, they my friend are.', NOW(), NOW()),
('तो', 'hi', 'en', 'to', 'अगर आप चाहें, तो हम चल सकते हैं।', 'Agar aap chaahein, to hum chal sakte hain.', 'If you wish, then we can go.', 'If you wish, then we walk can.', NOW(), NOW()),
('ही', 'hi', 'en', 'hi', 'मैं अभी ही आया हूँ।', 'Main abhi hi aaya hoon.', 'I have just arrived.', 'I now only arrived am.', NOW(), NOW()),
('भी', 'hi', 'en', 'bhi', 'मैं भी आपके साथ चलूँगा।', 'Main bhi aapke saath chalunga.', 'I will also come with you.', 'I also your with will walk.', NOW(), NOW()),
('था', 'hi', 'en', 'tha', 'कल मौसम अच्छा था।', 'Kal mausam accha tha.', 'The weather was good yesterday.', 'Yesterday weather good was.', NOW(), NOW()),
('जाना', 'hi', 'en', 'jaana', 'मुझे अब जाना चाहिए।', 'Mujhe ab jaana chahiye.', 'I should go now.', 'Me now to go should.', NOW(), NOW()),
('इस', 'hi', 'en', 'is', 'इस बारे में आपकी क्या राय है?', 'Is baare mein aapki kya raay hai?', 'What is your opinion about this?', 'This about in your what opinion is?', NOW(), NOW()),
('उस', 'hi', 'en', 'us', 'कृपया उस कमरे में जाइए।', 'Kripaya us kamre mein jaaiye.', 'Please go into that room.', 'Please that room in go.', NOW(), NOW()),
('बहुत', 'hi', 'en', 'bahut', 'आपका बहुत धन्यवाद।', 'Aapka bahut dhanyavaad.', 'Thank you very much.', 'Your very thank you.', NOW(), NOW()),
('हम', 'hi', 'en', 'hum', 'हम आपकी प्रतीक्षा कर रहे हैं।', 'Hum aapki pratiksha kar rahe hain.', 'We are waiting for you.', 'We your waiting doing are.', NOW(), NOW()),
('कोई', 'hi', 'en', 'koi', 'क्या कोई प्रश्न है?', 'Kya koi prashn hai?', 'Is there any question?', 'What any question is?', NOW(), NOW()),
('तक', 'hi', 'en', 'tak', 'मैं शाम तक काम करूँगा।', 'Main shaam tak kaam karunga.', 'I will work until the evening.', 'I evening until work will do.', NOW(), NOW()),
('बात', 'hi', 'en', 'baat', 'मुझे आपसे एक ज़रूरी बात करनी है।', 'Mujhe aapse ek zaroori baat karni hai.', 'I need to talk to you about something important.', 'Me you with one important matter to do is.', NOW(), NOW()),
('आना', 'hi', 'en', 'aana', 'आप फिर कब आएँगे?', 'Aap phir kab aayenge?', 'When will you come again?', 'You again when will come?', NOW(), NOW()),
('रहा', 'hi', 'en', 'raha', 'आप क्या कर रहे हैं?', 'Aap kya kar rahe hain?', 'What are you doing?', 'You what doing are?', NOW(), NOW()),
('अपना', 'hi', 'en', 'apna', 'कृपया अपना ध्यान रखें।', 'Kripaya apna dhyaan rakhein.', 'Please take care of yourself.', 'Please own care keep.', NOW(), NOW()),
('कुछ', 'hi', 'en', 'kuchh', 'क्या आप कुछ लेना पसंद करेंगे?', 'Kya aap kuchh lena pasand karenge?', 'Would you like to have something?', 'What you something to take like will do?', NOW(), NOW()),
('काम', 'hi', 'en', 'kaam', 'आपका काम सराहनीय है।', 'Aapka kaam sarahaniya hai.', 'Your work is commendable.', 'Your work commendable is.', NOW(), NOW()),
('समय', 'hi', 'en', 'samay', 'आपके पास समय है?', 'Aapke paas samay hai?', 'Do you have time?', 'Your near time is?', NOW(), NOW()),
('लोग', 'hi', 'en', 'log', 'वहाँ बहुत सारे लोग थे।', 'Vahaan bahut saare log the.', 'There were many people there.', 'There many people were.', NOW(), NOW()),
('लेकिन', 'hi', 'en', 'lekin', 'मैं आना चाहता था, लेकिन मुझे देर हो गई।', 'Main aana chahta tha, lekin mujhe der ho gayi.', 'I wanted to come, but I got late.', 'I to come wanted, but me late happened.', NOW(), NOW()),
('अगर', 'hi', 'en', 'agar', 'अगर आपको कोई आपत्ति न हो, तो मैं यहाँ बैठ सकता हूँ।', 'Agar aapko koi aapatti na ho, to main yahaan baith sakta hoon.', 'If you have no objection, I can sit here.', 'If you to any objection not be, then I here sit can.', NOW(), NOW()),
('या', 'hi', 'en', 'ya', 'आप चाय लेंगे या कॉफ़ी?', 'Aap chai lenge ya coffee?', 'Will you have tea or coffee?', 'You tea will take or coffee?', NOW(), NOW()),
('घर', 'hi', 'en', 'ghar', 'आपका घर कहाँ है?', 'Aapka ghar kahaan hai?', 'Where is your house?', 'Your house where is?', NOW(), NOW()),
('साथ', 'hi', 'en', 'saath', 'क्या मैं आपके साथ आ सकता हूँ?', 'Kya main aapke saath aa sakta hoon?', 'May I come with you?', 'What I your with come can?', NOW(), NOW()),
('मेरा', 'hi', 'en', 'mera', 'यह मेरा सौभाग्य है।', 'Yah mera saubhagya hai.', 'This is my good fortune.', 'This my good fortune is.', NOW(), NOW()),
('आपका', 'hi', 'en', 'aapka', 'आपकी सलाह बहुत उपयोगी थी।', 'Aapki salaah bahut upyogi thi.', 'Your advice was very useful.', 'Your advice very useful was.', NOW(), NOW()),
('सब', 'hi', 'en', 'sab', 'सब लोग यहाँ उपस्थित हैं।', 'Sab log yahaan upasthit hain.', 'Everyone is present here.', 'All people here present are.', NOW(), NOW()),
('मुझे', 'hi', 'en', 'mujhe', 'मुझे आपसे मिलकर ख़ुशी हुई।', 'Mujhe aapse milkar khushi hui.', 'I am pleased to meet you.', 'Me you with having met happiness happened.', NOW(), NOW()),
('देना', 'hi', 'en', 'dena', 'क्या आप मुझे अपनी कलम दे सकते हैं?', 'Kya aap mujhe apni kalam de sakte hain?', 'Can you give me your pen?', 'What you me your pen give can?', NOW(), NOW()),
('लेना', 'hi', 'en', 'lena', 'कृपया यह लीजिए।', 'Kripaya yah lijiye.', 'Please take this.', 'Please this take.', NOW(), NOW()),
('देखना', 'hi', 'en', 'dekhna', 'क्या आपने ताजमहल देखा है?', 'Kya aapne Taj Mahal dekha hai?', 'Have you seen the Taj Mahal?', 'What you Taj Mahal seen have?', NOW(), NOW()),
('अच्छा', 'hi', 'en', 'accha', 'यह एक बहुत अच्छा विचार है।', 'Yah ek bahut accha vichaar hai.', 'This is a very good idea.', 'This a very good idea is.', NOW(), NOW()),
('बड़ा', 'hi', 'en', 'bada', 'यह एक बड़ा शहर है।', 'Yah ek bada shahar hai.', 'This is a big city.', 'This a big city is.', NOW(), NOW()),
('दिन', 'hi', 'en', 'din', 'आपका दिन शुभ हो।', 'Aapka din shubh ho.', 'Have a good day.', 'Your day auspicious be.', NOW(), NOW()),
('आज', 'hi', 'en', 'aaj', 'आज मौसम बहुत सुहावना है।', 'Aaj mausam bahut suhaavna hai.', 'The weather is very pleasant today.', 'Today weather very pleasant is.', NOW(), NOW()),
('कल', 'hi', 'en', 'kal', 'हम कल इस पर चर्चा करेंगे।', 'Hum kal is par charcha karenge.', 'We will discuss this tomorrow.', 'We tomorrow this on discussion will do.', NOW(), NOW()),
('यहाँ', 'hi', 'en', 'yahaan', 'कृपया यहाँ हस्ताक्षर कीजिए।', 'Kripaya yahaan hastakshar kijiye.', 'Please sign here.', 'Please here signature do.', NOW(), NOW()),
('वहाँ', 'hi', 'en', 'vahaan', 'कृपया वहाँ प्रतीक्षा करें।', 'Kripaya vahaan pratiksha karein.', 'Please wait there.', 'Please there wait do.', NOW(), NOW()),
('कहाँ', 'hi', 'en', 'kahaan', 'आप कहाँ रहते हैं?', 'Aap kahaan rehte hain?', 'Where do you live?', 'You where live?', NOW(), NOW()),
('कैसे', 'hi', 'en', 'kaise', 'मैं आपकी मदद कैसे कर सकता हूँ?', 'Main aapki madad kaise kar sakta hoon?', 'How can I help you?', 'I your help how do can?', NOW(), NOW()),
('कब', 'hi', 'en', 'kab', 'आपकी बैठक कब है?', 'Aapki baithak kab hai?', 'When is your meeting?', 'Your meeting when is?', NOW(), NOW()),
('क्यों', 'hi', 'en', 'kyon', 'आप ऐसा क्यों सोचते हैं?', 'Aap aisa kyon sochte hain?', 'Why do you think so?', 'You so why think?', NOW(), NOW()),
('कौन', 'hi', 'en', 'kaun', 'दरवाज़े पर कौन है?', 'Darwaze par kaun hai?', 'Who is at the door?', 'Door at who is?', NOW(), NOW()),
('फिर', 'hi', 'en', 'phir', 'हम फिर मिलेंगे।', 'Hum phir milenge.', 'We will meet again.', 'We again will meet.', NOW(), NOW()),
('पानी', 'hi', 'en', 'paani', 'कृपया मुझे एक गिलास पानी दीजिए।', 'Kripaya mujhe ek gilaas paani dijiye.', 'Please give me a glass of water.', 'Please me one glass water give.', NOW(), NOW()),
('खाना', 'hi', 'en', 'khana', 'क्या आप खाना खाएँगे?', 'Kya aap khana khayenge?', 'Will you have food?', 'What you food will eat?', NOW(), NOW()),
('बोलना', 'hi', 'en', 'bolna', 'आप बहुत अच्छी हिंदी बोलते हैं।', 'Aap bahut acchi Hindi bolte hain.', 'You speak Hindi very well.', 'You very good Hindi speak.', NOW(), NOW()),
('सुनना', 'hi', 'en', 'sunna', 'कृपया मेरी बात ध्यान से सुनिए।', 'Kripaya meri baat dhyaan se suniye.', 'Please listen to me carefully.', 'Please my talk attention with listen.', NOW(), NOW()),
('समझना', 'hi', 'en', 'samajhna', 'क्या आप मेरी बात समझ रहे हैं?', 'Kya aap meri baat samajh rahe hain?', 'Are you understanding what I am saying?', 'What you my talk understanding are?', NOW(), NOW()),
('जानना', 'hi', 'en', 'jaanna', 'मैं आपको जानता हूँ।', 'Main aapko jaanta hoon.', 'I know you.', 'I you know.', NOW(), NOW()),
('चाहिए', 'hi', 'en', 'chahiye', 'हमें समय पर पहुँचना चाहिए।', 'Hamein samay par pahunchna chahiye.', 'We should arrive on time.', 'Us time on to arrive should.', NOW(), NOW()),
('सकता', 'hi', 'en', 'sakta', 'क्या आप मेरी मदद कर सकते हैं?', 'Kya aap meri madad kar sakte hain?', 'Can you help me?', 'What you my help do can?', NOW(), NOW()),
('पास', 'hi', 'en', 'paas', 'मेरे पास एक सुझाव है।', 'Mere paas ek sujhaav hai.', 'I have a suggestion.', 'My near one suggestion is.', NOW(), NOW()),
('अब', 'hi', 'en', 'ab', 'अब हमें निकलना चाहिए।', 'Ab hamein nikalna chahiye.', 'We should leave now.', 'Now us to leave should.', NOW(), NOW()),
('पहले', 'hi', 'en', 'pehle', 'कृपया बोलने से पहले सोचें।', 'Kripaya bolne se pehle sochein.', 'Please think before you speak.', 'Please speaking from before think.', NOW(), NOW()),
('बाद', 'hi', 'en', 'baad', 'खाने के बाद हम बात करेंगे।', 'Khane ke baad hum baat karenge.', 'We will talk after eating.', 'Eating of after we talk will do.', NOW(), NOW()),
('रात', 'hi', 'en', 'raat', 'शुभ रात्रि।', 'Shubh raatri.', 'Good night.', 'Auspicious night.', NOW(), NOW()),
('नाम', 'hi', 'en', 'naam', 'आपका शुभ नाम क्या है?', 'Aapka shubh naam kya hai?', 'What is your good name?', 'Your auspicious name what is?', NOW(), NOW()),
('छोटा', 'hi', 'en', 'chhota', 'यह एक छोटा सा उपहार है।', 'Yah ek chhota sa uphaar hai.', 'This is a small gift.', 'This a small particle gift is.', NOW(), NOW()),
('नया', 'hi', 'en', 'naya', 'आपको नई नौकरी के लिए बधाई।', 'Aapko nayi naukri ke liye badhaai.', 'Congratulations on your new job.', 'You to new job for congratulations.', NOW(), NOW()),
('क्योंकि', 'hi', 'en', 'kyunki', 'मैं नहीं आ सका क्योंकि मैं व्यस्त था।', 'Main nahin aa saka kyunki main vyast tha.', 'I couldn''t come because I was busy.', 'I not come could because I busy was.', NOW(), NOW()),
('इसलिए', 'hi', 'en', 'isliye', 'वे बीमार थे, इसलिए वे नहीं आए।', 'Ve bimaar the, isliye ve nahin aaye.', 'He was sick, therefore he did not come.', 'He sick was, therefore he not came.', NOW(), NOW()),
('हाँ', 'hi', 'en', 'haan', 'जी हाँ, यह सही है।', 'Jee haan, yah sahi hai.', 'Yes, this is correct.', 'Respectful particle yes, this correct is.', NOW(), NOW()),
('कृपया', 'hi', 'en', 'kripaya', 'कृपया शांत रहें।', 'Kripaya shaant rahein.', 'Please remain silent.', 'Please silent remain.', NOW(), NOW()),
('धन्यवाद', 'hi', 'en', 'dhanyavaad', 'आपकी सहायता के लिए धन्यवाद।', 'Aapki sahayata ke liye dhanyavaad.', 'Thank you for your assistance.', 'Your assistance for thank you.', NOW(), NOW()),
('पूछना', 'hi', 'en', 'poochhna', 'मैं आपसे कुछ पूछना चाहता हूँ।', 'Main aapse kuchh poochna chahta hoon.', 'I want to ask you something.', 'I you from something to ask want.', NOW(), NOW()),
('बताना', 'hi', 'en', 'batana', 'कृपया मुझे सही समय बताइए।', 'Kripaya mujhe sahi samay bataiye.', 'Please tell me the correct time.', 'Please me correct time tell.', NOW(), NOW()),
('सोचना', 'hi', 'en', 'sochna', 'मुझे इस प्रस्ताव पर सोचना होगा।', 'Mujhe is prastaav par sochna hoga.', 'I will have to think about this proposal.', 'Me this proposal on to think will be.', NOW(), NOW()),
('चलना', 'hi', 'en', 'chalna', 'क्या हम अब चलें?', 'Kya hum ab chalein?', 'Shall we go now?', 'What we now go?', NOW(), NOW()),
('बैठना', 'hi', 'en', 'baithna', 'कृपया यहाँ बैठिए।', 'Kripaya yahaan baithiye.', 'Please sit here.', 'Please here sit.', NOW(), NOW()),
('अंदर', 'hi', 'en', 'andar', 'कृपया अंदर आइए।', 'Kripaya andar aaiye.', 'Please come inside.', 'Please inside come.', NOW(), NOW()),
('बाहर', 'hi', 'en', 'baahar', 'कृपया बाहर प्रतीक्षा करें।', 'Kripaya baahar pratiksha karein.', 'Please wait outside.', 'Please outside wait do.', NOW(), NOW()),
('सुबह', 'hi', 'en', 'subah', 'शुभ प्रभात। आप कैसे हैं?', 'Shubh prabhaat. Aap kaise hain?', 'Good morning. How are you?', 'Auspicious morning. You how are?', NOW(), NOW()),
('शाम', 'hi', 'en', 'shaam', 'हम शाम को मिलेंगे।', 'Hum shaam ko milenge.', 'We will meet in the evening.', 'We evening at will meet.', NOW(), NOW()),
('हमेशा', 'hi', 'en', 'hamesha', 'वह हमेशा दूसरों की मदद करते हैं।', 'Vah hamesha doosron ki madad karte hain.', 'He/She always helps others.', 'He always others of help does.', NOW(), NOW()),
('माफ़ कीजिए', 'hi', 'en', 'maaf kijiye', 'माफ़ कीजिए, मुझे देर हो गई।', 'Maaf kijiye, mujhe der ho gayi.', 'Sorry, I am late.', 'Forgive do, me late happened.', NOW(), NOW()),
('नमस्कार', 'hi', 'en', 'namaskar', 'नमस्कार, आपसे मिलकर अच्छा लगा।', 'Namaskar, aapse milkar accha laga.', 'Hello, it was nice to meet you.', 'Greetings, you with having met good felt.', NOW(), NOW());

