-- Add More Hindi Character Guide Data
-- This migration updates existing characters and adds new ones to the Hindi character guide
-- Uses UPSERT to replace existing entries or insert new ones

-- Insert/Update characters from first set
INSERT INTO character_guide (language, start_sound, character_name, character_context, created_at, updated_at)
VALUES
    ('hi', 'a', 'Allan K', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'aj', 'Efe Ajagba', 'Boxer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'av', 'Avatar Aang', 'Avatar: The Last Airbender', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'an', 'Anakin Skywalker', 'Star Wars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ak', 'Akainu', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'as', 'Asta', 'Black Clover', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ba', 'Baji', 'Tokyo Revengers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'bi', 'Bilbo Baggins', 'Lord of the Rings', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'bl', 'Blackbeard', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'br', 'Brook', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ch', 'Chopper', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'cr', 'Crocodile', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'da', 'Darkest', 'Beta Squad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'de', 'DeMar DeRozan', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'di', 'Dio Brando', 'Jojo''s Bizzare Adventures', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'do', 'Doflamingo', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'du', 'Durant, Kevin', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'dr', 'Draken', 'Tokyo Revengers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'e', 'Eren Yeager', 'Attack on Titan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'el', 'Elvis Presley', 'Singer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'en', 'Jin Enjoji', 'Dandadan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ey', 'Ace', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ez', 'Ezra', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fa', 'Falco Grice', 'Attack on Titan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fe', 'Ferdinand Magellan', 'Historical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fi', 'Filly', 'Beta Squad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fo', 'Forger, Loid', 'Spy Family', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fr', 'Franky', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ga', 'Gaara', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'gi', 'Gintoki', 'Gintama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'go', 'Gol D. Roger', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ha', 'Harry Potter', 'Harry Potter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'he', 'Hendricksen', 'The Seven Deadly Sins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ho', 'Jose Manalo', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'i', 'Ichigo', 'Bleach', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'is', 'Yoichi Isagi', 'Blue Lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'it', 'Itachi', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ja', 'Ja Morant', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'je', 'Kenny "The Jet" Smith', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ji', 'Jimbei', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'jo', 'Joey De Leon', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'kh', 'Khabib Nurmagomedov', 'UFC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ka', 'Kakashi', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ke', 'Kenny', 'Beta Squad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ki', 'Kisaki', 'Tokyo Revengers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ko', 'Koby', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ku', 'Kuzan (Aokiji)', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'kr', 'Krillin', 'Dragon Ball', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ky', 'Kyrie Irving', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'le', 'LeBron James', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'li', 'Lee Su-ho', 'True Beauty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'lo', 'Law', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'lu', 'Luffy', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ma', 'Mikey', 'Tokyo Revengers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'me', 'Megumi Fushiguro', 'Jujutsu Kaisen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'mi', 'Mitsui', 'Slam Dunk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'mo', 'Momonga/Ainz Ooal Gown', 'Overlord', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'mu', 'Muzan Kibutsuji', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'na', 'Naruto', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ne', 'Neji', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ni', 'Niko', 'Beta Squad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'nu', 'Nuno Bettencourt', 'Musician', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'o', 'Orochimaru', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'on', 'Onyok Velasco', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pa', 'Patrick Star', 'Spongebob Squarepants', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pe', 'Petelgeuse Romanée-Conti', 'Re:Zero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pi', 'Picollo', 'Dragon Ball', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pl', 'Plankton', 'Plankton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'po', 'Pooh', 'Winnie the Pooh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pu', 'Pooh', 'Winnie the Pooh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'py', 'Pycelle', 'Game of Thrones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'qu', 'Queen', 'Band', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ra', 'Randy Orton', 'WWE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 're', 'Rengoku', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ro', 'Robin Padilla', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ru', 'Rukawa', 'Slam Dunk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'sa', 'Sanji', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'so', 'Suneo', 'Doraemon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'su', 'Suneo', 'Doraemon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'se', 'Sendou', 'Slam Dunk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ce', 'Sendou', 'Slam Dunk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'si', 'Pascal Siakam', 'NBA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'sh', 'Shanks', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ta', 'Tanjiro', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'te', 'Tengen Uzui', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ti', 'Tito Sotto', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'to', 'Toby', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'tu', 'Keith Thurman', 'Boxer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'tr', 'Trunks', 'Dragon Ball', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'u', 'Usain Bolt', 'Athlete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 've', 'Vegeta', 'Dragon Ball', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'vi', 'Vic Sotto', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'vo', 'Voltes V', 'Anime', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'vu', 'Voltes V', 'Anime', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'wa', 'Wally Bayola', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ya', 'Yami Sukehiro', 'Black Clover', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ye', 'Yeti', 'Abominable Snowman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'yu', 'Usopp', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'zo', 'Zoro', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (language, start_sound)
DO UPDATE SET
    character_name = EXCLUDED.character_name,
    character_context = EXCLUDED.character_context,
    updated_at = CURRENT_TIMESTAMP;

-- Insert/Update characters from second set
INSERT INTO character_guide (language, start_sound, character_name, character_context, created_at, updated_at)
VALUES
    ('hi', 'a', 'Alison', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ar', 'Arthur Pencilgon', 'Shangri-la Frontier', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ai', 'Ai Hoshino', 'Oshi no ko', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'am', 'Ami Mizuno', 'Sailor Moon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'an', 'Anne Curtis', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ba', 'Barbie', 'Fictional Character', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'be', 'Belmere', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'bi', 'Big Mom', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'bo', 'Boa', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'br', 'Brienne of Tarth', 'Game of Thrones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'bu', 'Bulma', 'Dragon Ball', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ch', 'Chinatsu', 'Blue Box', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'cl', 'Claudine Barretto', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'da', 'Darna', 'Filipino Character', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'the', 'Darna', 'Filipino Character', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'de', 'Demi Lovato', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'di', 'Dina Bonnevie', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'thi', 'Dina Bonnevie', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'do', 'Dory', 'Finding Nemo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'dr', 'Drew Barrymore', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'e', 'Erza Scarlet', 'Fairy Tail', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'em', 'Emily', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'es', 'Spencer', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fa', 'Fana', 'Black Clover', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fi', 'Fiona Frost', 'Spy Family', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fo', 'Forger Yor', 'Spy Family', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fl', 'Fleur Delacour', 'Harry Potter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fr', 'Freiren', 'Frieren', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'fu', 'Fujiko Mine', 'Lupin the 3rd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ge', 'Gerda', 'Snow Queen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'gi', 'Ginko Yurishiro', 'Yurikuma Arashi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'go', 'Rachelle Ann Go', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ha', 'Hange Zoe', 'Attack on Titan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'hi', 'Hinata', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ho', 'Hoshino Ai', 'Oshi no ko', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'hu', 'Hua Mulan', 'Mulan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'i', 'Ino', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'is', 'Isabelle Daza', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'je', 'Jenna', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ju', 'Julia Barreto', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ka', 'Kanao', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ki', 'Kim Chiu', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ko', 'Konan', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ku', 'Kurisu Makise', 'Steins;Gate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'la', 'Lala', 'Teletubbies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'le', 'Leia Organa', 'Star Wars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'li', 'Lisa Soberano', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'lu', 'Lucy Heartfilia', 'Fairy Tail', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ma', 'Maomao', 'The Apothecary Diaries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'me', 'Maine Mendoza', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'mi', 'Mitsuri', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'mo', 'Momo Ayase', 'Dandadan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'mu', 'Mulan', 'Mulan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'na', 'Nami', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ne', 'Nezuko', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'no', 'Nobara Kugisaki', 'Jujutsu Kaisen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'nu', 'Nui Harime', 'Kill la Kill', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'o', 'Olivia Rodrigo', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ol', 'Olivia Rodrigo', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'op', 'Oprah Winfrey', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'of', 'Oprah Winfrey', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'on', 'Ontan', 'Dededede', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pa', 'Pauleen Luna', 'Eat Bulaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pe', 'Perona', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pi', 'Pia Wurtzbach', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'pl', 'Plum Pudding', 'Strawberry Shortcake', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'po', 'Pocahontas', 'Disney Character', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ra', 'Ram', 'Re:Zero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 're', 'Rem', 'Re:Zero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ro', 'Robin', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'sa', 'Sakura', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'se', 'Serena Dalrymple', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'sh', 'Shinobu', 'Demon Slayer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'si', 'Cece', 'Pretty Little Liars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'so', 'Sophie Turner', 'Game of Thrones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'st', 'Storm', 'X-men', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ta', 'Takagi', 'Teasing Master Takagi-san', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'te', 'Temari', 'Naruto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ti', 'Tifa Lockhart', 'Final Fantasy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'to', 'Toni Gonzaga', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'tr', 'Trisha Elric', 'Full Metal Alchemist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'u', 'Ursula', 'The Little Mermaid', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 've', 'Venus Raj', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'vi', 'Vivi Nefertari', 'One Piece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'wa', 'Wonder Woman', 'Fictional Character', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'we', 'Wendy''s', 'Brand', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'wi', 'Winona Ryder', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'wo', 'Wolke Hegenbarth', 'German Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'ye', 'Yeng Constantino', 'Filipino Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'yi', 'Yi Ding', 'Celebrity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('hi', 'yu', 'Yuki Itose', 'Sign of Affection', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (language, start_sound)
DO UPDATE SET
    character_name = EXCLUDED.character_name,
    character_context = EXCLUDED.character_context,
    updated_at = CURRENT_TIMESTAMP;
